"""Curated IT certificate seed data."""

CERTIFICATES_SEED = [
    # AWS
    {"slug": "aws-cloud-practitioner", "name": "AWS Certified Cloud Practitioner", "vendor": "AWS", "level": "beginner", "domain": "cloud", "price_usd": 100, "currency": "USD", "duration_minutes": 90, "num_questions": 65, "passing_score": 700, "description": "Foundational understanding of AWS Cloud, services, and terminology. Ideal for anyone new to cloud.", "prerequisites": "No prerequisites. Basic IT literacy recommended.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-cloud-practitioner/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-cloud-practitioner/AWS-Certified-Cloud-Practitioner_Exam-Guide.pdf", "videos": [{"title": "AWS Certified Cloud Practitioner Full Course - freeCodeCamp", "url": "https://www.youtube.com/watch?v=SOTamWNgDKc"}, {"title": "AWS CCP Crash Course - Stephane Maarek", "url": "https://www.youtube.com/watch?v=NhDYbskXRgc"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/14050/aws-certified-cloud-practitioner-official-practice-question-set-clf-c02-english"},
    {"slug": "aws-solutions-architect-associate", "name": "AWS Certified Solutions Architect – Associate", "vendor": "AWS", "level": "intermediate", "domain": "cloud", "price_usd": 150, "currency": "USD", "duration_minutes": 130, "num_questions": 65, "passing_score": 720, "description": "Design resilient, high-performing, secure, and cost-optimized architectures on AWS.", "prerequisites": "1+ year hands-on AWS experience recommended.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-solutions-architect-associate/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-sa-assoc/AWS-Certified-Solutions-Architect-Associate_Exam-Guide.pdf", "videos": [{"title": "AWS SAA-C03 Ultimate Guide - Stephane Maarek", "url": "https://www.youtube.com/watch?v=Ia-UEYYR44s"}, {"title": "AWS Solutions Architect Full Course - freeCodeCamp", "url": "https://www.youtube.com/watch?v=Ia-UEYYR44s"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/13266"},
    {"slug": "aws-developer-associate", "name": "AWS Certified Developer – Associate", "vendor": "AWS", "level": "intermediate", "domain": "cloud", "price_usd": 150, "currency": "USD", "duration_minutes": 130, "num_questions": 65, "passing_score": 720, "description": "Develop and maintain AWS-based applications with focus on core services, deployment, and debugging.", "prerequisites": "1+ year developing on AWS.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-developer-associate/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-dev-associate/AWS-Certified-Developer-Associate_Exam-Guide.pdf", "videos": [{"title": "AWS Developer Associate DVA-C02 - Stephane Maarek", "url": "https://www.youtube.com/watch?v=RrKRN9zRBWs"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/14051"},
    {"slug": "aws-sysops-associate", "name": "AWS Certified SysOps Administrator – Associate", "vendor": "AWS", "level": "intermediate", "domain": "cloud", "price_usd": 150, "currency": "USD", "duration_minutes": 180, "num_questions": 65, "passing_score": 720, "description": "Operate, manage, and deploy scalable, fault-tolerant systems on AWS.", "prerequisites": "1-2 years hands-on AWS operations.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-sysops-admin-associate/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-sysops-associate/AWS-Certified-SysOps-Administrator-Associate_Exam-Guide.pdf", "videos": [{"title": "AWS SysOps Administrator Course - A Cloud Guru", "url": "https://www.youtube.com/watch?v=vyRvPO-1lYo"}], "practice_url": "https://aws.amazon.com/certification/certification-prep/"},
    {"slug": "aws-solutions-architect-professional", "name": "AWS Certified Solutions Architect – Professional", "vendor": "AWS", "level": "expert", "domain": "cloud", "price_usd": 300, "currency": "USD", "duration_minutes": 180, "num_questions": 75, "passing_score": 750, "description": "Design complex, multi-tier, cost-optimized solutions on AWS at enterprise scale.", "prerequisites": "2+ years designing AWS cloud solutions.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-solutions-architect-professional/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-sa-pro/AWS-Certified-Solutions-Architect-Professional_Exam-Guide.pdf", "videos": [{"title": "AWS SAP-C02 Full Course - Stephane Maarek", "url": "https://www.youtube.com/watch?v=821T7mZq3SM"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/14054"},
    {"slug": "aws-security-specialty", "name": "AWS Certified Security – Specialty", "vendor": "AWS", "level": "expert", "domain": "security", "price_usd": 300, "currency": "USD", "duration_minutes": 170, "num_questions": 65, "passing_score": 750, "description": "Specialized security controls, identity and access management, and incident response on AWS.", "prerequisites": "5 years IT security + 2 years AWS security experience.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-security-specialty/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-security-spec/AWS-Certified-Security-Specialty_Exam-Guide.pdf", "videos": [{"title": "AWS Security Specialty Full Course", "url": "https://www.youtube.com/watch?v=teCQ4hLdc-o"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/14056"},

    # Azure
    {"slug": "az-900-azure-fundamentals", "name": "Microsoft Azure Fundamentals (AZ-900)", "vendor": "Microsoft", "level": "beginner", "domain": "cloud", "price_usd": 99, "currency": "USD", "duration_minutes": 85, "num_questions": 45, "passing_score": 700, "description": "Foundational knowledge of Azure cloud concepts, services, and governance.", "prerequisites": "None. Great starting point.", "validity_years": 0, "official_url": "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/", "docs_url": "https://learn.microsoft.com/en-us/certifications/resources/study-guides/az-900", "videos": [{"title": "AZ-900 Full Course - John Savill", "url": "https://www.youtube.com/watch?v=NKEFWyqJ5XA"}, {"title": "AZ-900 Study Cram - John Savill", "url": "https://www.youtube.com/watch?v=tQp1YkB2Tgs"}], "practice_url": "https://learn.microsoft.com/en-us/certifications/exams/az-900/practice/assessment"},
    {"slug": "az-104-azure-administrator", "name": "Microsoft Azure Administrator (AZ-104)", "vendor": "Microsoft", "level": "intermediate", "domain": "cloud", "price_usd": 165, "currency": "USD", "duration_minutes": 120, "num_questions": 60, "passing_score": 700, "description": "Implement, manage, and monitor Azure identity, governance, storage, compute, and virtual networks.", "prerequisites": "6+ months Azure administration.", "validity_years": 1, "official_url": "https://learn.microsoft.com/en-us/certifications/azure-administrator/", "docs_url": "https://learn.microsoft.com/en-us/certifications/resources/study-guides/az-104", "videos": [{"title": "AZ-104 Full Study Cram - John Savill", "url": "https://www.youtube.com/watch?v=VOod_VNgdJk"}], "practice_url": "https://learn.microsoft.com/en-us/certifications/exams/az-104/practice/assessment"},
    {"slug": "az-204-azure-developer", "name": "Microsoft Azure Developer Associate (AZ-204)", "vendor": "Microsoft", "level": "intermediate", "domain": "cloud", "price_usd": 165, "currency": "USD", "duration_minutes": 120, "num_questions": 55, "passing_score": 700, "description": "Design, build, test, and maintain cloud applications on Azure.", "prerequisites": "1-2 years professional development experience.", "validity_years": 1, "official_url": "https://learn.microsoft.com/en-us/certifications/azure-developer/", "docs_url": "https://learn.microsoft.com/en-us/certifications/resources/study-guides/az-204", "videos": [{"title": "AZ-204 Study Cram - John Savill", "url": "https://www.youtube.com/watch?v=zt-b62YQmB0"}], "practice_url": "https://learn.microsoft.com/en-us/certifications/exams/az-204/practice/assessment"},
    {"slug": "az-305-azure-architect", "name": "Microsoft Azure Solutions Architect Expert (AZ-305)", "vendor": "Microsoft", "level": "expert", "domain": "cloud", "price_usd": 165, "currency": "USD", "duration_minutes": 120, "num_questions": 60, "passing_score": 700, "description": "Design cloud and hybrid solutions running on Microsoft Azure.", "prerequisites": "AZ-104 or equivalent + Azure design experience.", "validity_years": 1, "official_url": "https://learn.microsoft.com/en-us/certifications/azure-solutions-architect/", "docs_url": "https://learn.microsoft.com/en-us/certifications/resources/study-guides/az-305", "videos": [{"title": "AZ-305 Study Cram - John Savill", "url": "https://www.youtube.com/watch?v=bIH1GTB79k4"}], "practice_url": "https://learn.microsoft.com/en-us/certifications/exams/az-305/practice/assessment"},
    {"slug": "az-500-azure-security", "name": "Microsoft Azure Security Engineer (AZ-500)", "vendor": "Microsoft", "level": "expert", "domain": "security", "price_usd": 165, "currency": "USD", "duration_minutes": 120, "num_questions": 55, "passing_score": 700, "description": "Implement security controls, manage identity, and protect data on Azure.", "prerequisites": "Azure admin experience + security fundamentals.", "validity_years": 1, "official_url": "https://learn.microsoft.com/en-us/certifications/azure-security-engineer/", "docs_url": "https://learn.microsoft.com/en-us/certifications/resources/study-guides/az-500", "videos": [{"title": "AZ-500 Study Cram", "url": "https://www.youtube.com/watch?v=OWLQg-cX7Sc"}], "practice_url": "https://learn.microsoft.com/en-us/certifications/exams/az-500/practice/assessment"},

    # GCP
    {"slug": "gcp-cloud-digital-leader", "name": "Google Cloud Digital Leader", "vendor": "Google", "level": "beginner", "domain": "cloud", "price_usd": 99, "currency": "USD", "duration_minutes": 90, "num_questions": 60, "passing_score": 0, "description": "Articulate the capabilities of Google Cloud core products to further business objectives.", "prerequisites": "None.", "validity_years": 3, "official_url": "https://cloud.google.com/learn/certification/cloud-digital-leader", "docs_url": "https://cloud.google.com/learn/certification/guides/cloud-digital-leader", "videos": [{"title": "Cloud Digital Leader Full Course", "url": "https://www.youtube.com/watch?v=UGRDM86MBIQ"}], "practice_url": "https://cloud.google.com/learn/certification/practice-exams"},
    {"slug": "gcp-associate-cloud-engineer", "name": "Google Associate Cloud Engineer", "vendor": "Google", "level": "intermediate", "domain": "cloud", "price_usd": 125, "currency": "USD", "duration_minutes": 120, "num_questions": 50, "passing_score": 0, "description": "Deploy applications, monitor operations, and manage enterprise solutions on GCP.", "prerequisites": "6+ months hands-on GCP experience.", "validity_years": 3, "official_url": "https://cloud.google.com/learn/certification/cloud-engineer", "docs_url": "https://cloud.google.com/learn/certification/guides/cloud-engineer", "videos": [{"title": "GCP ACE Full Course - freeCodeCamp", "url": "https://www.youtube.com/watch?v=jpno8FSqpc8"}], "practice_url": "https://cloud.google.com/learn/certification/practice-exams"},
    {"slug": "gcp-professional-cloud-architect", "name": "Google Professional Cloud Architect", "vendor": "Google", "level": "expert", "domain": "cloud", "price_usd": 200, "currency": "USD", "duration_minutes": 120, "num_questions": 50, "passing_score": 0, "description": "Design, develop, and manage robust, secure, scalable GCP architectures.", "prerequisites": "3+ years industry experience with 1+ years on GCP.", "validity_years": 2, "official_url": "https://cloud.google.com/learn/certification/cloud-architect", "docs_url": "https://cloud.google.com/learn/certification/guides/professional-cloud-architect", "videos": [{"title": "GCP Cloud Architect Prep - Coursera", "url": "https://www.youtube.com/watch?v=uw3iN8yUgOU"}], "practice_url": "https://cloud.google.com/learn/certification/practice-exams"},
    {"slug": "gcp-professional-data-engineer", "name": "Google Professional Data Engineer", "vendor": "Google", "level": "expert", "domain": "data", "price_usd": 200, "currency": "USD", "duration_minutes": 120, "num_questions": 50, "passing_score": 0, "description": "Design and build data processing systems and machine learning models on GCP.", "prerequisites": "3+ years experience with 1+ years designing GCP solutions.", "validity_years": 2, "official_url": "https://cloud.google.com/learn/certification/data-engineer", "docs_url": "https://cloud.google.com/learn/certification/guides/data-engineer", "videos": [{"title": "GCP Data Engineer Course", "url": "https://www.youtube.com/watch?v=r_yYRvptI5o"}], "practice_url": "https://cloud.google.com/learn/certification/practice-exams"},

    # CompTIA
    {"slug": "comptia-a-plus", "name": "CompTIA A+", "vendor": "CompTIA", "level": "beginner", "domain": "hardware", "price_usd": 246, "currency": "USD", "duration_minutes": 90, "num_questions": 90, "passing_score": 675, "description": "Entry-level IT certification covering hardware, networking, mobile devices, and troubleshooting.", "prerequisites": "9-12 months hands-on experience recommended.", "validity_years": 3, "official_url": "https://www.comptia.org/certifications/a", "docs_url": "https://www.comptia.org/certifications/a", "videos": [{"title": "CompTIA A+ Full Course - Professor Messer", "url": "https://www.youtube.com/watch?v=Rkjr0qhcHnI"}], "practice_url": "https://www.comptia.org/training/practice-questions"},
    {"slug": "comptia-network-plus", "name": "CompTIA Network+", "vendor": "CompTIA", "level": "beginner", "domain": "networking", "price_usd": 358, "currency": "USD", "duration_minutes": 90, "num_questions": 90, "passing_score": 720, "description": "Core networking concepts, infrastructure, operations, and troubleshooting.", "prerequisites": "CompTIA A+ + 9-12 months networking experience.", "validity_years": 3, "official_url": "https://www.comptia.org/certifications/network", "docs_url": "https://www.comptia.org/certifications/network", "videos": [{"title": "Network+ Full Course - Professor Messer", "url": "https://www.youtube.com/watch?v=qYSFEQaTEQE"}], "practice_url": "https://www.comptia.org/training/practice-questions"},
    {"slug": "comptia-security-plus", "name": "CompTIA Security+", "vendor": "CompTIA", "level": "intermediate", "domain": "security", "price_usd": 392, "currency": "USD", "duration_minutes": 90, "num_questions": 90, "passing_score": 750, "description": "Baseline cybersecurity skills — threats, cryptography, IAM, risk management.", "prerequisites": "Network+ + 2 years IT admin experience recommended.", "validity_years": 3, "official_url": "https://www.comptia.org/certifications/security", "docs_url": "https://www.comptia.org/certifications/security", "videos": [{"title": "Security+ SY0-701 Full Course - Professor Messer", "url": "https://www.youtube.com/watch?v=0AigigM5_lI"}], "practice_url": "https://www.comptia.org/training/practice-questions"},
    {"slug": "comptia-cysa-plus", "name": "CompTIA CySA+", "vendor": "CompTIA", "level": "intermediate", "domain": "security", "price_usd": 392, "currency": "USD", "duration_minutes": 165, "num_questions": 85, "passing_score": 750, "description": "Cybersecurity analyst skills — threat detection, incident response, and vulnerability management.", "prerequisites": "Security+ + 4 years hands-on IT security experience.", "validity_years": 3, "official_url": "https://www.comptia.org/certifications/cybersecurity-analyst", "docs_url": "https://www.comptia.org/certifications/cybersecurity-analyst", "videos": [{"title": "CySA+ Full Course", "url": "https://www.youtube.com/watch?v=z8W4H8V4X4A"}], "practice_url": "https://www.comptia.org/training/practice-questions"},

    # Cisco
    {"slug": "cisco-ccna", "name": "Cisco Certified Network Associate (CCNA)", "vendor": "Cisco", "level": "intermediate", "domain": "networking", "price_usd": 300, "currency": "USD", "duration_minutes": 120, "num_questions": 100, "passing_score": 825, "description": "Foundation for networking careers — IP services, security, automation, and routing/switching.", "prerequisites": "1 year hands-on Cisco networking.", "validity_years": 3, "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html", "docs_url": "https://learningnetwork.cisco.com/s/ccna-exam-topics", "videos": [{"title": "CCNA Full Course - Jeremy's IT Lab", "url": "https://www.youtube.com/watch?v=H8W9oMNSuwo"}, {"title": "CCNA 200-301 - David Bombal", "url": "https://www.youtube.com/watch?v=OG-ttS_bx6Y"}], "practice_url": "https://learningnetwork.cisco.com/s/ccna"},
    {"slug": "cisco-ccnp-enterprise", "name": "Cisco Certified Network Professional (CCNP Enterprise)", "vendor": "Cisco", "level": "expert", "domain": "networking", "price_usd": 400, "currency": "USD", "duration_minutes": 120, "num_questions": 100, "passing_score": 825, "description": "Advanced networking skills — enterprise infrastructure, automation, and security.", "prerequisites": "CCNA + 3-5 years networking experience.", "validity_years": 3, "official_url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccnp-enterprise/index.html", "docs_url": "https://learningnetwork.cisco.com/s/ccnp-enterprise", "videos": [{"title": "CCNP ENCOR 350-401 Course", "url": "https://www.youtube.com/watch?v=U5Iw7CqrY10"}], "practice_url": "https://learningnetwork.cisco.com/s/ccnp-enterprise"},

    # Security
    {"slug": "cissp", "name": "CISSP – Certified Information Systems Security Professional", "vendor": "ISC2", "level": "expert", "domain": "security", "price_usd": 749, "currency": "USD", "duration_minutes": 240, "num_questions": 125, "passing_score": 700, "description": "The gold standard for cybersecurity leadership. Covers 8 domains of information security.", "prerequisites": "5+ years paid work experience in 2+ CISSP domains.", "validity_years": 3, "official_url": "https://www.isc2.org/certifications/cissp", "docs_url": "https://www.isc2.org/certifications/cissp/cissp-certification-exam-outline", "videos": [{"title": "CISSP Full Course - Destination Certification", "url": "https://www.youtube.com/watch?v=M1_v5HBVHXo"}, {"title": "CISSP Mind Map - Prabh Nair", "url": "https://www.youtube.com/watch?v=hpiEQlNAXcU"}], "practice_url": "https://www.isc2.org/certifications/cissp/practice-tests"},
    {"slug": "ceh", "name": "Certified Ethical Hacker (CEH)", "vendor": "EC-Council", "level": "intermediate", "domain": "security", "price_usd": 1199, "currency": "USD", "duration_minutes": 240, "num_questions": 125, "passing_score": 700, "description": "Master the art and science of ethical hacking, penetration testing, and vulnerability assessment.", "prerequisites": "2 years IT security or official EC-Council training.", "validity_years": 3, "official_url": "https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/", "docs_url": "https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/", "videos": [{"title": "CEH v12 Full Course", "url": "https://www.youtube.com/watch?v=fNzpcB7ODxQ"}], "practice_url": "https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/"},
    {"slug": "oscp", "name": "OSCP – Offensive Security Certified Professional", "vendor": "OffSec", "level": "expert", "domain": "security", "price_usd": 1649, "currency": "USD", "duration_minutes": 1440, "num_questions": 0, "passing_score": 70, "description": "Hands-on penetration testing certification. 24-hour practical exam. Industry-respected offensive security cred.", "prerequisites": "Solid networking + Linux + scripting knowledge.", "validity_years": 3, "official_url": "https://www.offsec.com/courses/pen-200/", "docs_url": "https://www.offsec.com/courses/pen-200/", "videos": [{"title": "OSCP Preparation Guide - TCM Security", "url": "https://www.youtube.com/watch?v=cTZjbmr1uHc"}], "practice_url": "https://www.offsec.com/labs/individual/"},
    {"slug": "cism", "name": "CISM – Certified Information Security Manager", "vendor": "ISACA", "level": "expert", "domain": "security", "price_usd": 760, "currency": "USD", "duration_minutes": 240, "num_questions": 150, "passing_score": 450, "description": "Management-focused security cert. Governance, risk management, incident response.", "prerequisites": "5 years information security management experience.", "validity_years": 3, "official_url": "https://www.isaca.org/credentialing/cism", "docs_url": "https://www.isaca.org/credentialing/cism/cism-exam", "videos": [{"title": "CISM Study Guide", "url": "https://www.youtube.com/watch?v=Xk2Cp_D5Bio"}], "practice_url": "https://www.isaca.org/credentialing/cism"},

    # Project & Data
    {"slug": "pmp", "name": "PMP – Project Management Professional", "vendor": "PMI", "level": "expert", "domain": "management", "price_usd": 555, "currency": "USD", "duration_minutes": 230, "num_questions": 180, "passing_score": 0, "description": "The world's leading project management certification. Predictive, agile, and hybrid approaches.", "prerequisites": "3-5 years PM experience + 35 hours PM education.", "validity_years": 3, "official_url": "https://www.pmi.org/certifications/project-management-pmp", "docs_url": "https://www.pmi.org/certifications/project-management-pmp/pmp-exam-prep", "videos": [{"title": "PMP Exam Full Course - Andrew Ramdayal", "url": "https://www.youtube.com/watch?v=owJx1ZBaWWs"}], "practice_url": "https://www.pmi.org/certifications/project-management-pmp"},
    {"slug": "csm-scrum-master", "name": "Certified ScrumMaster (CSM)", "vendor": "Scrum Alliance", "level": "beginner", "domain": "management", "price_usd": 995, "currency": "USD", "duration_minutes": 60, "num_questions": 50, "passing_score": 74, "description": "Foundational Scrum framework knowledge. Includes 2-day training + exam.", "prerequisites": "Must complete a CSM course.", "validity_years": 2, "official_url": "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster", "docs_url": "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster", "videos": [{"title": "Scrum Master Full Course", "url": "https://www.youtube.com/watch?v=SWDhGSZNF9M"}], "practice_url": "https://www.scrumalliance.org/get-certified"},
    {"slug": "aws-machine-learning-specialty", "name": "AWS Certified Machine Learning – Specialty", "vendor": "AWS", "level": "expert", "domain": "data", "price_usd": 300, "currency": "USD", "duration_minutes": 180, "num_questions": 65, "passing_score": 750, "description": "Design, implement, deploy, and maintain ML solutions on AWS.", "prerequisites": "1-2 years experience developing ML/DL workloads on AWS.", "validity_years": 3, "official_url": "https://aws.amazon.com/certification/certified-machine-learning-specialty/", "docs_url": "https://d1.awsstatic.com/training-and-certification/docs-ml/AWS-Certified-Machine-Learning-Specialty_Exam-Guide.pdf", "videos": [{"title": "AWS ML Specialty Course - Stephane Maarek", "url": "https://www.youtube.com/watch?v=CjBh8P8AXfE"}], "practice_url": "https://explore.skillbuilder.aws/learn/course/14052"},
    {"slug": "databricks-data-engineer-associate", "name": "Databricks Certified Data Engineer Associate", "vendor": "Databricks", "level": "intermediate", "domain": "data", "price_usd": 200, "currency": "USD", "duration_minutes": 90, "num_questions": 45, "passing_score": 70, "description": "Build and maintain data pipelines on Databricks Lakehouse.", "prerequisites": "6+ months experience with Databricks.", "validity_years": 2, "official_url": "https://www.databricks.com/learn/certification/data-engineer-associate", "docs_url": "https://www.databricks.com/learn/certification/data-engineer-associate", "videos": [{"title": "Databricks Data Engineer Course", "url": "https://www.youtube.com/watch?v=PIFL7W3DmaY"}], "practice_url": "https://www.databricks.com/learn/certification"},

    # DevOps
    {"slug": "cka-kubernetes", "name": "Certified Kubernetes Administrator (CKA)", "vendor": "Linux Foundation", "level": "intermediate", "domain": "devops", "price_usd": 395, "currency": "USD", "duration_minutes": 120, "num_questions": 17, "passing_score": 66, "description": "Hands-on Kubernetes cluster administration. Performance-based exam.", "prerequisites": "Solid Linux + container fundamentals.", "validity_years": 3, "official_url": "https://www.cncf.io/training/certification/cka/", "docs_url": "https://github.com/cncf/curriculum", "videos": [{"title": "CKA Full Course - KodeKloud", "url": "https://www.youtube.com/watch?v=8r7ZamLQXAM"}], "practice_url": "https://killer.sh/"},
    {"slug": "hashicorp-terraform-associate", "name": "HashiCorp Certified: Terraform Associate", "vendor": "HashiCorp", "level": "beginner", "domain": "devops", "price_usd": 70, "currency": "USD", "duration_minutes": 60, "num_questions": 57, "passing_score": 70, "description": "Cloud infrastructure automation with Terraform. IaC fundamentals.", "prerequisites": "Familiarity with cloud + basic scripting.", "validity_years": 2, "official_url": "https://developer.hashicorp.com/certifications/infrastructure-automation", "docs_url": "https://developer.hashicorp.com/terraform/tutorials/certification-003", "videos": [{"title": "Terraform Associate Course - HashiCorp", "url": "https://www.youtube.com/watch?v=SPcwo0Gq9T8"}], "practice_url": "https://developer.hashicorp.com/certifications"},
    {"slug": "docker-certified-associate", "name": "Docker Certified Associate", "vendor": "Docker", "level": "intermediate", "domain": "devops", "price_usd": 195, "currency": "USD", "duration_minutes": 90, "num_questions": 55, "passing_score": 65, "description": "Container fundamentals, orchestration, security, and networking with Docker.", "prerequisites": "6+ months Docker experience.", "validity_years": 2, "official_url": "https://www.docker.com/certification/", "docs_url": "https://docs.docker.com/", "videos": [{"title": "Docker Certified Associate Course", "url": "https://www.youtube.com/watch?v=fqMOX6JJhGo"}], "practice_url": "https://www.docker.com/certification/"},

    # RedHat / Linux
    {"slug": "rhcsa", "name": "Red Hat Certified System Administrator (RHCSA)", "vendor": "Red Hat", "level": "intermediate", "domain": "os", "price_usd": 500, "currency": "USD", "duration_minutes": 180, "num_questions": 0, "passing_score": 210, "description": "Performance-based Linux admin cert on RHEL. Highly respected in enterprise.", "prerequisites": "1+ year Linux administration.", "validity_years": 3, "official_url": "https://www.redhat.com/en/services/certification/rhcsa", "docs_url": "https://www.redhat.com/en/services/training/rh124-red-hat-system-administration-i", "videos": [{"title": "RHCSA EX200 Full Course", "url": "https://www.youtube.com/watch?v=fSCz1PBGss0"}], "practice_url": "https://www.redhat.com/en/services/certification/rhcsa"},

    # Salesforce
    {"slug": "salesforce-admin", "name": "Salesforce Certified Administrator", "vendor": "Salesforce", "level": "beginner", "domain": "crm", "price_usd": 200, "currency": "USD", "duration_minutes": 105, "num_questions": 60, "passing_score": 65, "description": "Manage and configure Salesforce for users and business processes.", "prerequisites": "6+ months hands-on Salesforce experience.", "validity_years": 1, "official_url": "https://trailhead.salesforce.com/en/credentials/administrator/", "docs_url": "https://trailhead.salesforce.com/help?article=Salesforce-Certified-Administrator-Exam-Guide", "videos": [{"title": "Salesforce Admin Full Course", "url": "https://www.youtube.com/watch?v=t1eu-fT8jUY"}], "practice_url": "https://trailhead.salesforce.com/en/credentials/administrator"},

    # Google Data
    {"slug": "google-data-analytics", "name": "Google Data Analytics Professional Certificate", "vendor": "Google", "level": "beginner", "domain": "data", "price_usd": 49, "currency": "USD", "duration_minutes": 0, "num_questions": 0, "passing_score": 0, "description": "Entry-level data analytics via Coursera. Self-paced, includes hands-on projects with SQL, R, and Tableau.", "prerequisites": "None.", "validity_years": 0, "official_url": "https://www.coursera.org/professional-certificates/google-data-analytics", "docs_url": "https://www.coursera.org/professional-certificates/google-data-analytics", "videos": [{"title": "Google Data Analytics Preview", "url": "https://www.youtube.com/watch?v=oNCzn4uYtaU"}], "practice_url": "https://www.coursera.org/professional-certificates/google-data-analytics"},
]
